[build]
  command = "npm run build:netlify"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false"
  NEXT_TELEMETRY_DISABLED = "1"
  # Secrets scanning configuration - exclude build output, docs, and email templates
  SECRETS_SCAN_OMIT_PATHS = ".next/**,.netlify/**,node_modules/**,.env.example,.env.production.example,docs/**,email-templates/**,*.md"
  # Exclude SENDGRID_FROM_NAME from secrets scanning (it's just the app name, not a secret)
  SECRETS_SCAN_OMIT_KEYS = "SENDGRID_FROM_NAME"

# Build cache configuration
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

# Redirects handled by Next.js

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
